### ISSUE TITLE
Create posts list

### ISSUE THREAD

**Issue by Fir0w** [Fir0w/post-app-react#9]
Create a component "PostsList".
This component will simply map through "Post" component a specific amount and render in the homepage.

**Comment by VicDosya** [comment]
In this component, We will have the placeholder data that you created.
add more posts data inside it so we can test multiple posts.

Then in the JSX, we will simply use .map(), something like this:
for example:
data.map((post, index) => (
        <Post key={index} title={post.postTitle} profile={post.profileName} />
))
